"""Runtime fragments for the structured X64 backend."""

from x64 import I, M, MS, R, LabelRef, Symbol


FULL_RUNTIME = "full"


def emit_runtime_data(x64, program):
    string_globals = {}
    x64.data_zero("_written", 4)
    x64.data_zero("_heap", 8)
    x64.data_zero("_argv", 8)
    x64.data_bytes("_newline", [10])
    x64.data_bytes("_cstr_panic_prefix", list(b"panic line "))
    x64.data_bytes("_cstr_panic_suffix", list(b": invalid cstr"))
    for glob in program.globals:
        if glob.name == "argv":
            continue
        data_label = _data_label(glob.name)
        header_label = _header_label(glob.name)
        values = list(glob.init.encode("ascii")) + [0]
        string_globals[glob.name] = (header_label, data_label, len(glob.init))
        x64.data_bytes(data_label, values)
        x64.data_zero(header_label, 24)
    return string_globals


def emit_startup_hook_call(x64):
    x64.inst("sub", R("rsp"), I(32))
    x64.inst("call", Symbol("__epx_runtime_start"))
    x64.inst("add", R("rsp"), I(32))


def append_runtime_helpers(x64, policy=FULL_RUNTIME):
    if policy != FULL_RUNTIME:
        raise RuntimeError(f"unsupported X64 runtime policy: {policy}")
    _emit_runtime_start(x64)
    emit_x64_runtime_helpers(x64)


def _emit_runtime_start(x64):
    x64.label("__epx_runtime_start")
    x64.inst("push", R("rbp"))
    x64.inst("mov", R("rbp"), R("rsp"))
    x64.inst("sub", R("rsp"), I(32))
    x64.inst("call", Symbol("GetProcessHeap"))
    x64.inst("add", R("rsp"), I(32))
    x64.inst("mov", MS("_heap"), R("rax"))
    x64.inst("sub", R("rsp"), I(32))
    x64.inst("call", Symbol("__epx_argv_init"))
    x64.inst("add", R("rsp"), I(32))
    x64.inst("mov", MS("_argv"), R("rax"))
    x64.inst("pop", R("rbp"))
    x64.inst("ret")



def emit_ep_wrapper(x64, public_name, primitive_name):
    x64.label(public_name)
    x64.inst("jmp", LabelRef(primitive_name))


def emit_x64_runtime_helpers(x64):
    # Public __ep_* helper symbols are semantic-layer entry points. For now
    # these wrappers tail-jump to __epx_* x64 primitives; later commits can
    # replace individual wrappers with MIR/Epic implementations without
    # changing frontend/codegen call sites.
    emit_ep_wrapper(x64, "__ep_cstr", "__epx_cstr")
    emit_ep_wrapper(x64, "__ep_write_file", "__epx_write_file")
    emit_ep_wrapper(x64, "__ep_read_file", "__epx_read_file")
    emit_ep_wrapper(x64, "__ep_system_cmd", "__epx_system_cmd")
    emit_ep_wrapper(x64, "__ep_print_str", "__epx_print_str")
    emit_ep_wrapper(x64, "__ep_print_newline", "__epx_print_newline")
    emit_epx_alloc(x64)
    emit_epx_cstr(x64)
    emit_epx_write_file(x64)
    emit_epx_read_file(x64)
    emit_epx_system_cmd(x64)
    emit_epx_argv_init(x64)
    emit_epx_print_str(x64)
    emit_epx_print_newline(x64)
    emit_epx_slice_oob(x64)
    emit_epx_null_deref(x64)

def _data_label(name):
    return name + "_data"


def _header_label(name):
    return name + "_header"

def emit_epx_alloc(x):
    x.label("__epx_alloc")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("mov", R("r8"), R("rcx"))
    x.inst("mov", R("rcx"), MS("_heap"))
    x.inst("mov", R("rdx"), I(8))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("HeapAlloc"))
    x.inst("add", R("rsp"), I(32))
    x.inst("pop", R("rbp"))
    x.inst("ret")

def emit_epx_cstr(x):
    x.label("__epx_cstr")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("sub", R("rsp"), I(96))
    x.inst("mov", M("rbp", -8), R("rcx"))
    x.inst("mov", M("rbp", -16), R("rdx"))
    x.inst("test", R("rcx"), R("rcx"))
    x.inst("jz", LabelRef("__epx_cstr.fail"))
    x.inst("mov", R("r8"), M("rcx"))
    x.inst("test", R("r8"), R("r8"))
    x.inst("jz", LabelRef("__epx_cstr.fail"))
    x.inst("mov", R("r9"), M("rcx", 8))
    x.inst("cmp", R("r9"), I(0))
    x.inst("jl", LabelRef("__epx_cstr.fail"))
    x.inst("mov", R("r10"), I(0))
    x.label("__epx_cstr.loop")
    x.inst("cmp", R("r10"), R("r9"))
    x.inst("jge", LabelRef("__epx_cstr.tail"))
    x.inst("mov", R("r11"), R("r8"))
    x.inst("add", R("r11"), R("r10"))
    x.inst("movzx", R("rax"), M("r11", 0, 1))
    x.inst("test", R("rax"), R("rax"))
    x.inst("jz", LabelRef("__epx_cstr.fail"))
    x.inst("add", R("r10"), I(1))
    x.inst("jmp", LabelRef("__epx_cstr.loop"))
    x.label("__epx_cstr.tail")
    x.inst("mov", R("r11"), R("r8"))
    x.inst("add", R("r11"), R("r9"))
    x.inst("movzx", R("rax"), M("r11", 0, 1))
    x.inst("test", R("rax"), R("rax"))
    x.inst("jnz", LabelRef("__epx_cstr.fail"))
    x.inst("mov", R("rax"), R("r8"))
    x.inst("add", R("rsp"), I(96))
    x.inst("pop", R("rbp"))
    x.inst("ret")
    x.label("__epx_cstr.fail")
    x.inst("mov", R("rcx"), I(-11))
    x.inst("call", Symbol("GetStdHandle"))
    x.inst("mov", M("rbp", -24), R("rax"))
    x.inst("mov", R("rcx"), R("rax"))
    x.inst("lea", R("rdx"), MS("_cstr_panic_prefix"))
    x.inst("mov", R("r8"), I(11))
    x.inst("lea", R("r9"), MS("_written"))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("call", Symbol("WriteFile"))
    x.inst("mov", R("rcx"), M("rbp", -16))
    x.inst("call", Symbol("__ep_str_from_i64"))
    x.inst("mov", R("rcx"), R("rax"))
    x.inst("call", Symbol("__epx_print_str"))
    x.inst("mov", R("rcx"), M("rbp", -24))
    x.inst("lea", R("rdx"), MS("_cstr_panic_suffix"))
    x.inst("mov", R("r8"), I(14))
    x.inst("lea", R("r9"), MS("_written"))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("call", Symbol("WriteFile"))
    x.inst("mov", R("rcx"), M("rbp", -24))
    x.inst("lea", R("rdx"), MS("_newline"))
    x.inst("mov", R("r8"), I(1))
    x.inst("lea", R("r9"), MS("_written"))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("call", Symbol("WriteFile"))
    x.inst("mov", R("rcx"), I(1))
    x.inst("call", Symbol("ExitProcess"))

def emit_epx_write_file(x):
    x.label("__epx_write_file")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("sub", R("rsp"), I(96))
    x.inst("mov", M("rbp", -56), R("rdx"))
    x.inst("mov", R("rdx"), R("r8"))
    x.inst("call", Symbol("__epx_cstr"))
    x.inst("mov", M("rbp", -8), R("rax"))
    x.inst("mov", R("rdx"), M("rbp", -56))
    x.inst("mov", R("rax"), M("rdx"))
    x.inst("mov", M("rbp", -16), R("rax"))
    x.inst("mov", R("rax"), M("rdx", 8))
    x.inst("mov", M("rbp", -24), R("rax"))
    x.inst("mov", R("rcx"), M("rbp", -8))
    x.inst("mov", R("rdx"), I(0x40000000))
    x.inst("mov", R("r8"), I(0))
    x.inst("mov", R("r9"), I(0))
    x.inst("sub", R("rsp"), I(56))
    x.inst("mov", M("rsp", 32), I(2))
    x.inst("mov", M("rsp", 40), I(0x80))
    x.inst("mov", M("rsp", 48), I(0))
    x.inst("call", Symbol("CreateFileA"))
    x.inst("add", R("rsp"), I(56))
    x.inst("mov", R("rcx"), I(-1))
    x.inst("cmp", R("rax"), R("rcx"))
    x.inst("jz", LabelRef("__epx_write_file.fail"))
    x.inst("mov", M("rbp", -32), R("rax"))
    x.inst("mov", R("rcx"), M("rbp", -32))
    x.inst("mov", R("rdx"), M("rbp", -16))
    x.inst("mov", R("r8"), M("rbp", -24))
    x.inst("lea", R("r9"), M("rbp", -40))
    x.inst("mov", M("rbp", -40), I(0))
    x.inst("sub", R("rsp"), I(40))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("call", Symbol("WriteFile"))
    x.inst("add", R("rsp"), I(40))
    x.inst("mov", R("rcx"), M("rbp", -32))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("CloseHandle"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rax"), M("rbp", -40))
    x.inst("jmp", LabelRef("__epx_write_file.done"))
    x.label("__epx_write_file.fail")
    x.inst("mov", R("rax"), I(-1))
    x.label("__epx_write_file.done")
    x.inst("add", R("rsp"), I(96))
    x.inst("pop", R("rbp"))
    x.inst("ret")

def emit_epx_read_file(x):
    x.label("__epx_read_file")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("sub", R("rsp"), I(112))
    x.inst("call", Symbol("__epx_cstr"))
    x.inst("mov", M("rbp", -8), R("rax"))
    x.inst("mov", R("rcx"), M("rbp", -8))
    x.inst("mov", R("rdx"), I(0x80000000))
    x.inst("mov", R("r8"), I(1))
    x.inst("mov", R("r9"), I(0))
    x.inst("sub", R("rsp"), I(56))
    x.inst("mov", M("rsp", 32), I(3))
    x.inst("mov", M("rsp", 40), I(0x80))
    x.inst("mov", M("rsp", 48), I(0))
    x.inst("call", Symbol("CreateFileA"))
    x.inst("add", R("rsp"), I(56))
    x.inst("mov", R("rcx"), I(-1))
    x.inst("cmp", R("rax"), R("rcx"))
    x.inst("jz", LabelRef("__epx_read_file.empty"))
    x.inst("mov", M("rbp", -16), R("rax"))
    x.inst("mov", R("rcx"), MS("_heap"))
    x.inst("mov", R("rdx"), I(8))
    x.inst("mov", R("r8"), I(24))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("HeapAlloc"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", M("rbp", -56), R("rax"))
    x.inst("mov", R("rcx"), M("rbp", -16))
    x.inst("mov", R("rdx"), I(0))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("GetFileSize"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", M("rbp", -24), R("rax"))
    x.inst("mov", M("rbp", -64), R("rax"))
    x.inst("mov", R("rcx"), MS("_heap"))
    x.inst("mov", R("rdx"), I(8))
    x.inst("mov", R("r8"), M("rbp", -64))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("HeapAlloc"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", M("rbp", -32), R("rax"))
    x.inst("mov", R("rcx"), M("rbp", -16))
    x.inst("mov", R("rdx"), M("rbp", -32))
    x.inst("mov", R("r8"), M("rbp", -24))
    x.inst("lea", R("r9"), M("rbp", -40))
    x.inst("mov", M("rbp", -40), I(0))
    x.inst("sub", R("rsp"), I(40))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("call", Symbol("ReadFile"))
    x.inst("add", R("rsp"), I(40))
    x.inst("mov", R("rcx"), M("rbp", -16))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("CloseHandle"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rcx"), M("rbp", -56))
    x.inst("mov", R("rax"), M("rbp", -32))
    x.inst("mov", M("rcx"), R("rax"))
    x.inst("mov", R("rax"), M("rbp", -40))
    x.inst("mov", M("rcx", 8), R("rax"))
    x.inst("mov", R("rax"), M("rbp", -64))
    x.inst("mov", M("rcx", 16), R("rax"))
    x.inst("mov", R("rax"), R("rcx"))
    x.inst("jmp", LabelRef("__epx_read_file.done"))
    x.label("__epx_read_file.empty")
    x.inst("mov", R("rcx"), I(0))
    x.inst("mov", R("rdx"), I(0))
    x.inst("call", Symbol("__ep_slice_u8_alloc"))
    x.label("__epx_read_file.done")
    x.inst("add", R("rsp"), I(112))
    x.inst("pop", R("rbp"))
    x.inst("ret")

def emit_epx_system_cmd(x):
    x.label("__epx_system_cmd")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("sub", R("rsp"), I(272))
    x.inst("call", Symbol("__epx_cstr"))
    x.inst("mov", M("rbp", -16), R("rax"))
    x.inst("mov", R("rax"), I(0))
    x.inst("mov", M("rbp", -8), R("rax"))
    for off in range(96, 224, 8):
        x.inst("mov", M("rsp", off), I(0))
    x.inst("mov", M("rsp", 96), I(104))
    x.inst("mov", R("rcx"), I(0))
    x.inst("mov", R("rdx"), M("rbp", -16))
    x.inst("mov", R("r8"), I(0))
    x.inst("mov", R("r9"), I(0))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("mov", M("rsp", 40), I(0))
    x.inst("mov", M("rsp", 48), I(0))
    x.inst("mov", M("rsp", 56), I(0))
    x.inst("lea", R("rax"), M("rsp", 96))
    x.inst("mov", M("rsp", 64), R("rax"))
    x.inst("lea", R("rax"), M("rsp", 200))
    x.inst("mov", M("rsp", 72), R("rax"))
    x.inst("call", Symbol("CreateProcessA"))
    x.inst("test", R("rax"), R("rax"))
    x.inst("jnz", LabelRef("__epx_system_cmd.ok"))
    x.inst("mov", R("rax"), I(-1))
    x.inst("jmp", LabelRef("__epx_system_cmd.done"))
    x.label("__epx_system_cmd.ok")
    x.inst("mov", R("rcx"), M("rsp", 200))
    x.inst("mov", R("rdx"), I(-1))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("WaitForSingleObject"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rcx"), M("rsp", 200))
    x.inst("lea", R("rdx"), M("rbp", -8))
    x.inst("mov", M("rbp", -8), I(0))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("GetExitCodeProcess"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rcx"), M("rsp", 200))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("CloseHandle"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rcx"), M("rsp", 208))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("CloseHandle"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rax"), M("rbp", -8))
    x.label("__epx_system_cmd.done")
    x.inst("add", R("rsp"), I(272))
    x.inst("pop", R("rbp"))
    x.inst("ret")

def emit_epx_argv_init(x):
    x.label("__epx_argv_init")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("sub", R("rsp"), I(128))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("GetCommandLineA"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rsi"), R("rax"))
    x.inst("mov", R("rcx"), MS("_heap"))
    x.inst("mov", R("rdx"), I(8))
    x.inst("mov", R("r8"), I(24))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("HeapAlloc"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", M("rbp", -8), R("rax"))
    x.inst("mov", R("rcx"), I(0))
    x.inst("mov", M("rax", 8), R("rcx"))
    x.inst("mov", R("rcx"), I(16))
    x.inst("mov", M("rax", 16), R("rcx"))
    x.inst("mov", R("rcx"), MS("_heap"))
    x.inst("mov", R("rdx"), I(8))
    x.inst("mov", R("r8"), I(128))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("HeapAlloc"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rcx"), M("rbp", -8))
    x.inst("mov", M("rcx"), R("rax"))
    x.label("__epx_argv_init.skip_ws")
    x.inst("movzx", R("rax"), M("rsi", 0, 1))
    x.inst("mov", R("rcx"), I(0))
    x.inst("cmp", R("rax"), R("rcx"))
    x.inst("jz", LabelRef("__epx_argv_init.done"))
    for value in (32, 9, 13, 10):
        x.inst("mov", R("rcx"), I(value))
        x.inst("cmp", R("rax"), R("rcx"))
        x.inst("jz", LabelRef("__epx_argv_init.advance_ws"))
    x.inst("jmp", LabelRef("__epx_argv_init.arg_start"))
    x.label("__epx_argv_init.advance_ws")
    x.inst("add", R("rsi"), I(1))
    x.inst("jmp", LabelRef("__epx_argv_init.skip_ws"))
    x.label("__epx_argv_init.arg_start")
    x.inst("mov", R("r11"), I(0))
    x.inst("mov", R("rcx"), I(34))
    x.inst("cmp", R("rax"), R("rcx"))
    x.inst("jnz", LabelRef("__epx_argv_init.start_plain"))
    x.inst("mov", R("r11"), I(1))
    x.inst("add", R("rsi"), I(1))
    x.label("__epx_argv_init.start_plain")
    x.inst("mov", M("rbp", -24), R("rsi"))
    x.inst("mov", R("r10"), I(0))
    x.label("__epx_argv_init.scan")
    x.inst("movzx", R("rax"), M("rsi", 0, 1))
    x.inst("mov", R("rcx"), I(0))
    x.inst("cmp", R("rax"), R("rcx"))
    x.inst("jz", LabelRef("__epx_argv_init.store"))
    x.inst("test", R("r11"), R("r11"))
    x.inst("jnz", LabelRef("__epx_argv_init.scan_quoted"))
    for value in (32, 9, 13, 10):
        x.inst("mov", R("rcx"), I(value))
        x.inst("cmp", R("rax"), R("rcx"))
        x.inst("jz", LabelRef("__epx_argv_init.store"))
    x.inst("jmp", LabelRef("__epx_argv_init.take"))
    x.label("__epx_argv_init.scan_quoted")
    x.inst("mov", R("rcx"), I(34))
    x.inst("cmp", R("rax"), R("rcx"))
    x.inst("jz", LabelRef("__epx_argv_init.store_quoted"))
    x.label("__epx_argv_init.take")
    x.inst("add", R("rsi"), I(1))
    x.inst("add", R("r10"), I(1))
    x.inst("jmp", LabelRef("__epx_argv_init.scan"))
    x.label("__epx_argv_init.store_quoted")
    x.inst("add", R("rsi"), I(1))
    x.label("__epx_argv_init.store")
    x.inst("mov", M("rbp", -32), R("rsi"))
    x.inst("mov", M("rbp", -40), R("r10"))
    x.inst("mov", R("rcx"), MS("_heap"))
    x.inst("mov", R("rdx"), I(8))
    x.inst("mov", R("r8"), I(16))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("HeapAlloc"))
    x.inst("add", R("rsp"), I(32))
    x.inst("mov", R("rcx"), M("rbp", -24))
    x.inst("mov", M("rax"), R("rcx"))
    x.inst("mov", R("rcx"), M("rbp", -40))
    x.inst("mov", M("rax", 8), R("rcx"))
    x.inst("mov", R("rdx"), M("rbp", -8))
    x.inst("mov", R("rcx"), M("rdx", 8))
    x.inst("mov", R("r8"), M("rdx"))
    x.inst("mov", R("r9"), R("rcx"))
    x.inst("add", R("r9"), R("r9"))
    x.inst("add", R("r9"), R("r9"))
    x.inst("add", R("r9"), R("r9"))
    x.inst("add", R("r8"), R("r9"))
    x.inst("mov", M("r8"), R("rax"))
    x.inst("add", R("rcx"), I(1))
    x.inst("mov", M("rdx", 8), R("rcx"))
    x.inst("mov", R("rsi"), M("rbp", -32))
    x.inst("jmp", LabelRef("__epx_argv_init.skip_ws"))
    x.label("__epx_argv_init.done")
    x.inst("mov", R("rax"), M("rbp", -8))
    x.inst("add", R("rsp"), I(128))
    x.inst("pop", R("rbp"))
    x.inst("ret")

def emit_epx_print_str(x):
    x.label("__epx_print_str")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("sub", R("rsp"), I(48))
    x.inst("mov", M("rbp", -8), R("rcx"))
    x.inst("mov", R("rcx"), I(-11))
    x.inst("call", Symbol("GetStdHandle"))
    x.inst("mov", R("rcx"), R("rax"))
    x.inst("mov", R("rax"), M("rbp", -8))
    x.inst("mov", R("rdx"), M("rax"))
    x.inst("mov", R("r8"), M("rax", 8))
    x.inst("lea", R("r9"), MS("_written"))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("call", Symbol("WriteFile"))
    x.inst("add", R("rsp"), I(48))
    x.inst("pop", R("rbp"))
    x.inst("ret")

def emit_epx_print_newline(x):
    x.label("__epx_print_newline")
    x.inst("push", R("rbp"))
    x.inst("mov", R("rbp"), R("rsp"))
    x.inst("sub", R("rsp"), I(48))
    x.inst("mov", R("rcx"), I(-11))
    x.inst("call", Symbol("GetStdHandle"))
    x.inst("mov", R("rcx"), R("rax"))
    x.inst("lea", R("rdx"), MS("_newline"))
    x.inst("mov", R("r8"), I(1))
    x.inst("lea", R("r9"), MS("_written"))
    x.inst("mov", M("rsp", 32), I(0))
    x.inst("call", Symbol("WriteFile"))
    x.inst("add", R("rsp"), I(48))
    x.inst("pop", R("rbp"))
    x.inst("ret")

def emit_epx_slice_oob(x):
    x.label("__epx_slice_oob")
    x.inst("mov", R("rcx"), I(1))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("ExitProcess"))

def emit_epx_null_deref(x):
    x.label("__epx_null_deref")
    x.inst("mov", R("rcx"), I(1))
    x.inst("sub", R("rsp"), I(32))
    x.inst("call", Symbol("ExitProcess"))


