id = "epic"
name = "Epic"
version = "0.1.1"
schema_version = 1
authors = ["picasso250"]
description = "Epic language support for Zed"
repository = "https://github.com/picasso250/epic-lang"

[grammars.epic]
repository = "https://github.com/picasso250/epic-lang"
rev = "52e6a415d7d5fe677155b8525b3d38d02e4b1ecc"
path = "editors/zed/tree-sitter-epic"
