id = "epic"
name = "Epic"
version = "0.1.1"
schema_version = 1
authors = ["picasso250"]
description = "Epic language support for Zed"
repository = "https://github.com/picasso250/epic-lang"

[grammars.epic]
repository = "https://github.com/picasso250/epic-lang"
rev = "06fa9145c87b6cf1f610c531f2cb1b4664cf05c2"
path = "editors/zed/tree-sitter-epic"
