id = "epic"
name = "Epic"
version = "0.1.1"
schema_version = 1
authors = ["picasso250"]
description = "Epic language support for Zed"
repository = "https://github.com/picasso250/epic-lang"

[grammars.epic]
repository = "https://github.com/picasso250/epic-lang"
rev = "6e8ea2a18c2471f1d467f3a96e255de1d4e58668"
path = "editors/zed/tree-sitter-epic"
